### ISSUE TITLE
button - key/type redundancy

### ISSUE THREAD

**Issue by vlbee** [fac-13/VP-react-game#4]
I don't think we need to pass key and type into the button if they will be the same value. Just the key will suffice. 

![image](https://user-images.githubusercontent.com/32312712/40430670-8ef9bbbc-5e9d-11e8-9541-5d04c234e657.png)

**Comment by Parissai** [comment]
Replaced `return <Button key={btn.type} {...btn} />;` with `<Button key={btn.id} {...btn} />;`, got this error: 
>Each child in an array or iterator should have a unique "key" prop.
